name: Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install file and strings
        run: sudo apt-get update && sudo apt-get install -y file binutils
      - name: Install the package
        run: pip install ./backend pytest
      - name: Run pytest
        working-directory: backend
        run: PYTHONPATH=. pytest tests/
